cargo-features = ["edition"]

[package]
name = "ircparse"
version = "0.1.0"
authors = ["Wonwoo Choi <chwo9843@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.1"
nom = "4.0"
regex = "1.0"
